#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#

boost:
  - 1.74.0
boost_cpp:
  - 1.74.0
hdf5:
  - 1.10.6
lz4_c:
  - 1.9.3
numpy:
  - 1.17
python:
  - 3.7
zeromq:
  - 4.3.3

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  lz4-c:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  python:
    max_pin: x.x
  zeromq:
    max_pin: x.x

CONDA_BUILD_SYSROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
