#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#

libboost_devel:
  - '1.86'
libboost_python_devel:
  - '1.86'
hdf5:
  - 1.14.3
jsoncpp:
  - 1.9.6
libpng:
  - '1.6'
lz4_c:
  - 1.9.3
numpy:
  #- 1.26  # Same as conda-forge-pinning (on 2024-12-20), even though numpy 2.0 exists.
  - '2.0'
python:
  - 3.12.* *_cpython
python_impl:
  - cpython
zeromq:
  - 4.3.5

# conda-forge uses these zip_keys, so we do it here even though
# it's not necessary since we only use a single version of each.
zip_keys:
  -
    - python
    - numpy
    - python_impl

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  jsoncpp:
    max_pin: x.x.x
  lz4-c:
    max_pin: x.x.x
  python:
    max_pin: x.x
  zeromq:
    max_pin: x.x


# CONDA_BUILD_SYSROOT:
#   # Most conda-forge packages are compatible with MacOSX 10.9,
#   # but golang-1.16 requires at least MacOSX 10.13, so FlyEM uses 10.13 as our target across the board.
#   # (See the download page: https://go.dev/dl/)
#   #
#   # The simplest thing to do is to download the SDK from the release page in this repo:
#   # https://github.com/phracker/MacOSX-SDKs
#   # https://github.com/phracker/MacOSX-SDKs/releases
#   #
#   # Previously, we would use the XcodeLegacy script, via the following project,
#   # but it doesn't seem to work with new versions of Xcode.
#   # https://github.com/devernay/xcodelegacy
#   - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

# MACOSX_DEPLOYMENT_TARGET:
#   - 10.13
